# Generated by Django 4.2.3 on 2023-09-18 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title1', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('button_tag', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='slider_image/')),
            ],
        ),
        migrations.CreateModel(
            name='SubCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LetsShop_App.catagory', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Product_image1/')),
                ('image2', models.ImageField(upload_to='Product_image2/')),
                ('image3', models.ImageField(upload_to='Product_image3/')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prev_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('short_description', models.TextField()),
                ('top_seller', models.BooleanField(default=False)),
                ('deals_of_the_day', models.BooleanField(default=False)),
                ('trending_product', models.BooleanField(default=False)),
                ('featured_product', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('wish_list', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LetsShop_App.catagory', verbose_name='')),
                ('color', models.ManyToManyField(to='LetsShop_App.color')),
                ('condition', models.ManyToManyField(to='LetsShop_App.condition')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
                ('size', models.ManyToManyField(to='LetsShop_App.size')),
                ('sub_catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LetsShop_App.subcatagory', verbose_name='')),
            ],
        ),
    ]
