# Generated by Django 4.2.3 on 2023-09-18 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LetsShop_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LetsShop_App.catagory', verbose_name='Catagories'),
        ),
        migrations.CreateModel(
            name='SuperSubCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('SubCatagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LetsShop_App.subcatagory', verbose_name='')),
            ],
        ),
    ]
