# Generated by Django 4.2.3 on 2023-10-17 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LetsShop_App', '0002_alter_product_catagory_supersubcatagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='super_sub_catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LetsShop_App.supersubcatagory', verbose_name='Super-Sub-Catagory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Posted By'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LetsShop_App.subcatagory', verbose_name='Sub-Catagory'),
        ),
    ]
