# Generated by Django 4.2.3 on 2023-10-17 11:38

import LetsShop_App.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LetsShop_App', '0003_product_super_sub_catagory_alter_product_posted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='posted_by',
            field=models.ForeignKey(default=LetsShop_App.models.logedin_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Posted By'),
        ),
    ]
