# Generated by Django 4.2.3 on 2023-10-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetsShop_App', '0005_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
