# Generated by Django 4.2.3 on 2023-09-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetsShop_Accounts', '0005_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
